'''0. The Below Image gives idea about the dimension'''
<img src="array1.png" style= "width: 600px;height:300px"/>

In [ ]:
'''1. Let's see how can we see the data type and the dimension of an array
(4,) it means 4 rows and no columns.. as this is 1 dimensional array

ndim and shape are the attributes of array
'''

import numpy as np
f = np.array([1, 1, 2, 3])
print(f.ndim,f.shape)


In [2]:
'''
2. Always good to viualize in Spyder:

Create a 2 dimensional array manually by supplying the values
Of course, arrays of NumPy are not limited to one dimension. They are of arbitrary dimension. 
We create them by passing nested lists (or tuples) to the array method of numpy.
Comma is must between individual lists
'''
a = np.array([ [3.4,8.7,9.9], 
               [1.1,-7.8,-0.7],
               [4.1,12.3,4.8],
               [1.1,12.2,3.4]
             ])
print(a)
print(a.ndim,a.shape)

[[ 3.4  8.7  9.9]
 [ 1.1 -7.8 -0.7]
 [ 4.1 12.3  4.8]
 [ 1.1 12.2  3.4]]
2 (4, 3)


In [5]:
'''
3. Create a 3 dimensional array manually by supplying the values
Of course, arrays of NumPy are not limited to one dimension. They are of arbitrary dimension. 
We create them by passing nested lists (or tuples) to the array method of numpy.

'''
a = np.array([[[3.4, 8.7, 9.9], 
               [1.1, -7.8, -0.7],
               [4.1, 12.3, 4.8]]])
print(a)
print(a.ndim,a.shape)

[[[ 3.4  8.7  9.9]
  [ 1.1 -7.8 -0.7]
  [ 4.1 12.3  4.8]]]
3 (1, 3, 3)


In [2]:
'''3.2 Guess the Dimension of the below array
2,3,3 >> means an array with 2 arrays of each 3 rows and 3 columns
'''
import numpy as np
a = np.array([[[3.4, 8.7, 9.9], 
               [1.1, -7.8, -0.7],
               [4.1, 12.3, 4.8]],
              
               [[3.4, 8.7, 9.9], 
               [1.1, -7.8, -0.7],
               [4.1, 12.3, 4.8]],
               [[3.4, 8.7, 9.9], 
               [1.1, -7.8, -0.7],
               [4.1, 12.3, 4.8]]
             
             ])
print(a)
print(a.ndim,a.shape)

[[[ 3.4  8.7  9.9]
  [ 1.1 -7.8 -0.7]
  [ 4.1 12.3  4.8]]

 [[ 3.4  8.7  9.9]
  [ 1.1 -7.8 -0.7]
  [ 4.1 12.3  4.8]]

 [[ 3.4  8.7  9.9]
  [ 1.1 -7.8 -0.7]
  [ 4.1 12.3  4.8]]]
3 (3, 3, 3)


'''3.1 This image would help in the viualization of array in 3 D Array :)
Representation of 3D array in Tabular Format: 
A three – dimensional array with 3 array containing 3 rows and 3 columns is shown below:
'''

<img src="array3.jpg" style= "width: 600px;height:300px"/>