'''0. The Row and column adddress of the elements in 2D array'''
<img src="array2.png" style= "width: 400px;height:400px"/>

In [4]:
'''1. Slicing on a 2D array
Understand this is as first row and and first columns value

The address would be 0,0. 0th row and 0th column
'''
import numpy as np
a = np.array([ [3.4,8.7,9.9,10], 
               [1.1,-7.8,-0.7,11],
               [4.1,12.3,4.8,12],
             ])
print(a.shape)

# This is used to access the values at item level
a[0][0]

(3, 4)


3.4

In [3]:
'''2. Guess the ouput, as we are using the : and : all the values of the array would be returned 
'''
import numpy as np
a = np.array([ [3.4,8.7,9.9], 
               [1.1,-7.8,-0.7],
               [4.1,12.3,4.8],
               [1.1,12.2,3.4]
             ])
a[:][:]

array([[ 3.4,  8.7,  9.9],
       [ 1.1, -7.8, -0.7],
       [ 4.1, 12.3,  4.8],
       [ 1.1, 12.2,  3.4]])

In [5]:
'''3. Guess the ouput, the first row would be returned for all the columns :)
'''
import numpy as np
a = np.array([ [3.4,8.7,9.9], 
               [1.1,-7.8,-0.7],
               [4.1,12.3,4.8],
               [1.1,12.2,3.4]
             ])
a[0][:]

array([3.4, 8.7, 9.9])

In [8]:
'''3.1 What would be the dimesnion of the returned array.. any guess :)'''

import numpy as np
a = np.array([ [3.4,8.7,9.9], 
               [1.1,-7.8,-0.7],
               [4.1,12.3,4.8],
               [1.1,12.2,3.4]
             ])
k=a[0][:]

print(k,k.ndim, k.shape)

[3.4 8.7 9.9] 1 (3,)


In [5]:
'''4. Guess the ouput, this would now point to the row index 1 and column index 2
'''
import numpy as np
a = np.array([ [3.4,8.7,9.9], 
               [1.1,-7.8,-0.7],
               [4.1,12.3,4.8],
               [1.1,12.2,3.4]
             ])
a[1][2]

-0.7

In [6]:
'''4.1 Guess the ouput.. of the below code
'''
import numpy as np
a = np.array([ [3.4,8.7,9.9], 
               [1.1,-7.8,-0.7],
               [4.1,12.3,4.8],
               [1.1,12.2,3.4]
             ])
a[1][0:2]

array([ 1.1, -7.8])

In [9]:
'''5. Guess the ouput with a negative index

Does the negative index work?  if yes what would be the returned value ?
'''
import numpy as np
a = np.array([ [3.4,8.7,9.9], 
               [1.1,-7.8,-0.7],
               [4.1,12.3,4.8],
               [1.1,12.2,9.9]
             ])
a[-1][-1]

9.9

In [1]:
'''6. Do we have the concept of by
Guess the output of the below code
'''

import numpy as np
a = np.array([ [3.4,8.7,9.9], 
               [1.1,-7.8,-0.7],
               [4.1,12.3,4.8],
               [1.1,12.2,3.4]
             ])
a[1][::2]

array([ 1.1, -0.7])