In [1]:
'''
1. One of the famous module in Numpy used in Data science is the random module.
How can you have random numbers in array between 1 and 10.
We can call the randint function from the random module

size: It lets you choose the size of array
'''
# first 2 arguments are start and stop, and then is the dimension of the numpy array, the default start is 0
import numpy as np
np.random.randint(1,10, size=(3,4)) 

array([[7, 1, 1, 4],
       [7, 8, 1, 8],
       [2, 7, 5, 2]])

In [2]:
'''
2. one dimension #random numbers between 0 and 10 in different arrays
'''
import numpy as np
np.random.randint(10, size=6)

array([9, 6, 2, 6, 1, 9])

In [3]:
'''2.1 two dimensional, numbers between 0 and 10 and in 3 rows and 4 columns'''
np.random.randint(10, size=(3,4))

array([[2, 0, 9, 5],
       [7, 3, 7, 3],
       [0, 5, 5, 2]])

In [4]:
'''2.2 #Three dimension, when you run in spyder, 
focus on the index drop down and you can view the data from many dimensions

It basically means: 3 arrays with 4 rows and 5 columns :)
'''
x3 = np.random.randint(10, size=(3,4,5))
print(x3)

[[[0 3 3 9 5]
  [9 4 8 3 1]
  [0 1 8 5 2]
  [6 9 7 9 4]]

 [[3 3 8 7 8]
  [1 1 4 4 2]
  [1 7 1 1 5]
  [0 8 2 0 7]]

 [[8 6 1 9 6]
  [2 9 7 4 6]
  [2 4 1 3 4]
  [7 3 0 8 7]]]


In [14]:
'''
2.4. To see the dimension of the array, use the ndim method with the array names
'''
print(np.ndim(x1),np.ndim(x2),np.ndim(x3))

1 2 3


In [11]:
'''
3. Just random values between 0 and 1, just like rand() function in excel, 
always use spyder for the documentation and optional parameters
This would create a one dimensional array

Values would change for every run :) ...between 0 and 1
'''
import numpy as np
np.random.rand(5)

#This can be given as like this also, read it 1 row and 5 columns 
import numpy as np
np.random.rand(1,5)

array([0.43290447, 0.57962719, 0.64013714, 0.93563022, 0.54082711])

In [13]:
'''
3.1 Two dimensional array usuing random.rand. 3 rows and 5 columns with values between 0 and 1
'''
import numpy as np
np.random.rand(3,5)

array([[0.1947482 , 0.00242739, 0.3849944 , 0.33433575, 0.96010209],
       [0.54701502, 0.22736868, 0.7294633 , 0.27819422, 0.92049886],
       [0.02771183, 0.71443007, 0.97116795, 0.39557771, 0.64037313]])

In [14]:
'''
3.1 Three dimensional array using random.rand
3 arrays with 2 rows and 5 columns with values between 0 and 1
'''
import numpy as np
np.random.rand(3,2,5)

array([[[0.7121935 , 0.31787219, 0.6636324 , 0.47587691, 0.47916684],
        [0.15656382, 0.2458527 , 0.4984547 , 0.02634518, 0.81349673]],

       [[0.83540895, 0.39805239, 0.62667402, 0.18386306, 0.79191423],
        [0.03668438, 0.14581428, 0.82774092, 0.00417446, 0.91496752]],

       [[0.39631411, 0.47982285, 0.45647606, 0.53196096, 0.96274852],
        [0.2283355 , 0.59143928, 0.96249518, 0.64047818, 0.17788448]]])

In [2]:
'''4. With the seed value you can always get the same set of random numbers
Seed must be between 0 and 2**32 - 1

This seed would ensure that the values for every run are the same.
'''
import numpy as np
np.random.seed(0)
x1 = np.random.randint(1,10, size=(3,4)) 
print(x1)

[[6 1 4 4]
 [8 4 6 3]
 [5 8 7 9]]
